package questions.prepare;

/**
 * Reference: https://code-exercises.com/programming/medium/11/even-fibonacci-sum
 * Task: Write a method that returns the sum of all even Fibonacci numbers. Consider all
 * Fibonacci numbers that are less than or equal to n.
 * Each new element in the Fibonacci sequence is generated by adding the previous two elements.
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 */

public class FibonacciCANTEven
{
    public static void main(String[] args)
    {
        FibonacciCANTEven fibonacciCANTEven = new FibonacciCANTEven();
        System.out.println(fibonacciCANTEven.evenFibonacciSum(450));
    }

    /**
     * A method that sums all even numbers in the Fibonacci sequence for up to nth value in the sequence
     * @param n maximum value in the Fibonacci sequence
     * @return a sum of even fibonacci numbers in a sequence
     */
    public Integer evenFibonacciSum(Integer n)
    {
        if (n == 0)
        {
            return 0;
        }
        if (n == 1)
        {
            return 0;
        }
        int answer = 0;
        int value1 = 0;
        int value2 = 1;
        while (value2 <= n)
        {
            int temp = value2;
            value2+= value1;
            value1 = temp;
            if (value2 % 2 == 0 && value2 <= n)
            {
                answer += value2;
            }
        }
        return answer;
    }
}
